### ISSUE TITLE
remove unused ReporterObject and RepLogger modules

### ISSUE THREAD

**Issue by stdweird** [quattor/CAF#101]
They appear to be unused throughout quattor and they are untested.

**Comment by ned21** [comment]
Do we have a source code log to show when/why they were introduced? Or have they been deprecated by newer functions?

**Comment by stdweird** [comment]
@ned21 they are mentioned in the Changelog, not sure they were ever used for quattor, but possibly for another project that relied on CAF. i can try to get something from git history to clarify this.
