### ISSUE TITLE
get rid of TextRender format general

### ISSUE THREAD

**Issue by stdweird** [quattor/CAF#108]
The `Config::General` module should not be used to render configfiles, as it's can't guarantee consistent and correct output.

**Comment by stdweird** [comment]
see #107 and earlier #97

**Comment by stdweird** [comment]
@ned21 @piojo seems to have some recollection you are intersted or using this?

**Comment by ned21** [comment]
We have a couple of places where we are using it, mainly to create files in /etc/modprobe.d. I need to look into whether we can swap those out with a modern version of ncm-modprobe or not, although ISTR you wanted to move away from things like ncm-modprobe and replace it with ncm-metaconfig, in which case, what's the recommended way forward?

(I sent some example configs to Jindrich to share with you f2f.)

**Comment by stdweird** [comment]
@ned21 we should create a small TT file that produces the format. i'll check with jindrich how hard that can be. are you using `ncm-metaconfig` for it right now?

**Comment by ned21** [comment]
We have a bit of a haphazard collection of different approaches atm but we want to standardise on the "right" way to manage these files.

**Comment by stdweird** [comment]
`ncm-modprobe` is still needed for the `mkinitrd`, but should be expanded to support multiple files, and maybe even proper schema. however this is beyond this PR imho.

https://github.com/quattor/CCM/pull/73 should provide the `<key> <value>` you need for the examples mentioned above
