### ISSUE TITLE
review the current usage of `each`

### ISSUE THREAD

**Issue by stdweird** [quattor/CAF#109]
`each` is evil, and altough it can be used correctly, should be avoided at all costs. after learning the lesson once more (i ran into it previously, but somehow forgot), we should get rid of it.

the problem is that each sort-of remembers the last element it iterated over.
this has all sorts of nasty side effects, but the following example illustrates the danger of using each and stopping the iteration.

``` perl
#!/usr/bin/perl

use strict;
use warnings;

my %h = (
    a => 1,
    b => 2,
    );

sub bad
{
    my $stop = shift;
    while (my ($k, $v) = each(%h)) {
        print "$k $v\n";
        return if $stop;
    }
}

sub good
{
    my $stop = shift;
    foreach my $k (keys%h) {
        print "$k $h{$k}\n";
        return if $stop;
    }
}


print "bad\n";
bad(1);
bad();

print "good\n";
good(1);
good();
```

which gives output

```
bad
b 2
a 1
good
b 2
b 2
a 1
```

**Comment by jrha** [comment]
AFAICT `each` is only being used in:
- TextRender.pm
- ReporterMany.pm

**Comment by ned21** [comment]
Should we add a section on this to https://www.quattor.org/development/coding_style.html ?
