### ISSUE TITLE
no longer import functions from CAF modules 

### ISSUE THREAD

**Issue by stdweird** [quattor/CAF#131]
One of the current PRs (probably the cleanup in CAF::Object in https://github.com/quattor/CAF/pull/126)
causes the following to fail 
```
PERL5LIB=/usr/lib/perl/ perl -e 'use CAF::Process qw(execute)'
"execute" is not exported by the CAF::Process module
Can't continue after import errors at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```

The question is: is this supposed to work/ required?
it is backwards incompatible, but methods should be used directly anyway.

(The other question: why was this working before, or how did the changes break this)

**Comment by stdweird** [comment]
@jrha @ned21 feedback welcome

**Comment by stdweird** [comment]
@jrha to be closed after the RCs have been tested

**Comment by stdweird** [comment]
only occurrence of direct method import https://github.com/quattor/configuration-modules-core/pull/676

**Comment by jrha** [comment]
As discussed at today's stand-up, this functionality shouldn't be needed.

**Comment by jrha** [comment]
Fixed by merging quattor/configuration-modules-core#676.
