### ISSUE TITLE
CAF::FileReader example use does not work

### ISSUE THREAD

**Issue by ned21** [quattor/CAF#139]
CAF::FileReader includes the following sample code but [a search ](https://github.com/quattor/configuration-modules-core/search?utf8=%E2%9C%93&q=FileReader&type=Code) of the code base shows no actual examples of its use.

```
    use CAF::FileReader;
    my $fh = CAF::FileReader->open ("my/path");
    while (my $line = <$fh>) {
       # Do something
    }
```

In testing, this doesn't work. ```print "$fh"``` does work because of stringify().  This works:

```
my $fh = CAF::FileReader->open("/path/to/file");
foreach my $line (split(/\n/, "$fh")) {
    print "$line\n";
}
```

Unclear if this is a documentation bug or if filehandle syntax should work?

**Comment by stdweird** [comment]
@ned21 should work i think. it's simply `IO::String`. what perl/OS is this? (i'll try to reproduce asap)

**Comment by ned21** [comment]
I could reproduce on both RHEL5 and RHEL6.

rhel5 $ /usr/bin/perl -version
This is perl, v5.8.8 built for x86_64-linux-thread-multi

rhel6 $ /usr/bin/perl -v
This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi

perl-CAF is 14.10 but I couldn't see any changes since then that would change this.

**Comment by stdweird** [comment]
works fine with latest master on EL5
```
[quattor@localhost quattordev]$ cat /etc/hosts
# Do not remove the following line, or various programs
# that require network functionality will fail.
127.0.0.1		localhost.localdomain localhost
::1		localhost6.localdomain6 localhost6
[quattor@localhost quattordev]$ perl -e 'use CAF::FileReader; $fh = CAF::FileReader->new("/etc/hosts");print join("X", <$fh>),"\n";'
# Do not remove the following line, or various programs
X# that require network functionality will fail.
X127.0.0.1		localhost.localdomain localhost
X::1		localhost6.localdomain6 localhost6

[quattor@localhost quattordev]$ uname -a 
Linux localhost.localdomain 2.6.18-402.el5 #1 SMP Tue Feb 10 17:49:04 EST 2015 x86_64 x86_64 x86_64 GNU/Linux
[quattor@localhost quattordev]$ perl -v

This is perl, v5.8.8 built for x86_64-linux-thread-multi
[quattor@localhost quattordev]$ perl -e 'use IO::String; print $IO::String::VERSION,"\n";'
1.08
[quattor@localhost quattordev]$ rpm -q perl-IO-String
perl-IO-String-1.08-1.1.1

```

**Comment by stdweird** [comment]
we can add it as unittest to make sure the examples work.

**Comment by ned21** [comment]
I just installed perl-CAF 15.12 and it still doesn't work.

```
$ /usr/bin/perl -e 'use IO::String; print $IO::String::VERSION,"\n";'
1.08

$ cat /tmp/foo.pl 
#!/usr/bin/perl

use strict;
use warnings;

use lib '/usr/lib/perl';

use CAF::FileReader;

my $fh = CAF::FileReader->open("/etc/ms-release"); 

while (my $line = <$fh>) {
   print "$line\n";
}
$ /tmp/foo.pl 
$ 
$  cat /etc/ms-release 
aquilon/linux/6.1-x86_64/testing
```

**Comment by stdweird** [comment]
@ned21 the example is wrong, it has to be `->new`, not `->open` (i overlooked it completely)

**Comment by stdweird** [comment]
if you want to use `open`, you have to reseek to the  begin with `$fh->seek_begin` (it's basically what new does in `FileReader` (and not in eg Writer or Editor)

**Comment by ned21** [comment]
Thanks. That seems weird - open() is a synonym for new() in other modules and this code suggests it should result in the same method.
```
# Alias open to new.
no warnings 'redefine';
*__PACKAGE__::open = \&new;
use warnings;
```

**Comment by stdweird** [comment]
hmmm, that is weird. note that for the parent `IO::String` `open` is nto the same as `new`, so it's odd that `open` is redefined to `new`.

**Comment by stdweird** [comment]
this is indeed supposed to be like this.  expect a PR and unittetst soonish

**Comment by stdweird** [comment]
@ned21 i can fix it, but i don't understand what is going on. probably subtle differences between `use base`, `use parent` and friends.
