### ISSUE TITLE
CAF::Lock is not atomic

### ISSUE THREAD

**Issue by gombasg** [quattor/CAF#144]
Hi,

We've just run into two AII invocations trying to write the DHCP config file simultaneously. Although the aii-dhcpd module does use CAF::Lock, apparently CAF::Lock is not atomic. Take the following sample code:

```
#! /usr/bin/perl
use lib '/usr/lib/perl';
use CAF::Lock qw(FORCE_IF_STALE);
my $lock = CAF::Lock->new("/tmp/test.lock");
die("No lock") unless $lock->set_lock(6, 10, FORCE_IF_STALE);
```

strace tells this story:

```
stat("/tmp/test.lock", 0x711130)        = -1 ENOENT (No such file or directory)
open("/tmp/test.lock", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
lseek(3, 0, SEEK_CUR)                   = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
write(3, "3741", 4)                     = 4
close(3)                                = 0
stat("/tmp/test.lock", {st_mode=S_IFREG|0644, st_size=4, ...}) = 0
```

Note that the open() call misses `O_EXCL`; without that, two processes executing the same steps in parallel would happily end up both thinking they own the lock.

**Comment by stdweird** [comment]
@gombasg could this be related to #132?

**Comment by gombasg** [comment]
Yes, that's related, but the proposed solution is not quite there yet.

**Comment by stdweird** [comment]
@gombasg now we get
```
stat("/tmp/test.lock", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
open("/tmp/test.lock", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
ioctl(3, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, 0x7fffffffe1b0) = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
flock(3, LOCK_EX|LOCK_NB)               = 0
close(3)     
```
(to test with your code, you need https://github.com/quattor/CAF/pull/195, or add a `use CAF::Reporter`)

**Comment by jrha** [comment]
So is there a fix for this?

**Comment by stdweird** [comment]
@jrha i think it is fixed, but waiting for @gombasg to confirm

**Comment by jouvin** [comment]
I think it was the purpose on relying on flock() in CAF::Lock, isn't it?

**Comment by ttyS4** [comment]
@jouvin Yes, i think this was fixed by using flock in `CAF::Lock`.

**Comment by stdweird** [comment]
@gombasg ping?

**Comment by jouvin** [comment]
After discussion with Gabor, there was an agreement that CAF::Lock changes should have fixed this issue. Closing this issue: reopen it if needed.
