### ISSUE TITLE
CAF::FileWriter updates files in-place

### ISSUE THREAD

**Issue by ttyS4** [quattor/CAF#148]
It should create a new file and rename to do it atomically.

**Comment by stdweird** [comment]
care to elaborate a bit? maybe a test case/example?
CAF::FileWriter uses `LC::Check` to do the actual modifications

**Comment by ttyS4** [comment]
If a configuration is created with metaconfig what I see from strace is that the file is unlink-ed first and then opened write-only mode. This means if an application reads the file in-between it could read partial content.
I think it should create a new temporary file (if modification needed) and then do a rename to move to its intended name. I have not traced down to the actual code doing the work.

**Comment by stdweird** [comment]
@ttyS4 files are written using `https://github.com/quattor/CAF/blob/master/src/main/perl/FileWriter.pm#L186`, and what you are seeing is `https://github.com/quattor/LC/blob/master/src/main/perl/Check.pm#L906` (i didn't know the internals either, but the code confirms your strace data and it's scary indeed).

**Comment by ned21** [comment]
@stdweird Is there a plan here? Bring forward plans to remove LC::Check and handle writing the file within FileWriter?

**Comment by stdweird** [comment]
well, i'd say replace `LC::Check::file` with another (hopefully existing) library that does this atomically. replacing whole LC::Check will only take a lot longer. reinventing `LC::Check::file` is not something we should attempt imho, it's too much specialised work. on the short term, patching `LC::Check` might be considered.

**Comment by stdweird** [comment]
@ned21 e.g. review http://search.cpan.org/~jmates/File-AtomicWrite-1.16/lib/File/AtomicWrite.pm and use that in LC::Check::file or if good enough, in FileWriter?

**Comment by ned21** [comment]
The module looks comprehensive but I would be a little reluctant to introduce a dependency on yet another library for what is still a fairly simple operation. e.g. one of the modules on which we depend pollutes $@ which caused some odd bugs, etc. Admittedly File::AtomicWrite does appear to use die() to signal errors which is nice and modern but using a library does force us to respect their calling semantics which might not be exactly what we want. 

How much code is this to just put it into File::Writer? I had a look at some of the NoWorries modules but while atomic_write() is 15 lines it in turn relies on two more subs in a different module. OTOH the checksumming does look like a nice feature...

**Comment by stdweird** [comment]
@ned21 fairly simple? `LC::Check::file` supports backup, noaction, create missing parent dirs, set permissions/ownership, report changed content and i probably missed a few things. (the only thing we do not need is the not so nice exception handling system imho)
using a library is not that bad, certainly beats trying to write this ourself. as long as we wrap it in CAF, it's ok i think. i'll have a look at the NoWorries module.

**Comment by ned21** [comment]
If we didn't have a library then I would agree, but we already have CAF::FileWriter and CAF::Path so why do we need another layer of indirection? AtomicWrite is actually nicer than NoWorries in that it is fairly simple. NoWorries brings in a lot of code with many layers of abstraction.

I guess I am looking to simplify the code base rather than complicate it further. So if LC::Check::file was replaced by AtomicWrite, but I'd like to avoid adding yet another layer that a write goes through

**Comment by stdweird** [comment]
@ned21 i totally understand, but reinventing the wheel requires time and effort (which i don't have)

i'll try to identify the code blocks we need from `LC::Check::file` and how many lines of perl is required to replace it (from NoWorries of AtomicWrite), incl unittests. but if the required code is too large, using (yet another layer of) libraries makes sense from a maintenance point of view imho.

**Comment by stdweird** [comment]
so i read some code :smile: 
* NoWories::File is not atomic
* IO::AtomicFile is too simple
* File::AtomicWrite is nice 
  * goes to great lengths to make sure the tempfile is cleaned up when something goes wrong
  * checksum feature
  * the `safe_level` is a nice thing to use, didn't know it existed
  * supports setting ownership/mode and create directories
  * missing
   *  backup support: this is a real pity, as making a backup is basically another rename
   * reporting if something was modified: would have to check how this might work, requires to read the original file, and if this were done, might avoid a rename/backup if nothing was changed (now the rename always happens)

so AtomicWrite looks ideal if we would use a lib. it is now 350 lines of code (no comments/whitespace/docs) and similar amount of lines for the unittests. adding backup support and filechanges is maybe another100 lines (incl tests). 
so if we were to add this in CAF, it's not impossible codewise (some of the functionality would come from CAF::Path, some copied from e.g. atomicewrite and some would be new).

contributing the backup support and detecting if anything changed is also a possibilty, but then the maintainer should agree on the patches, or we would have to fork it (which is certainly not the intent, as it is even more work).
if only we had a summerstudent who knew perl :smile:

**Comment by ned21** [comment]
After discussion I am good with using perl-File-AtomicWrite, shipped by quattor as an external RPM. We also discussed the potential issues caused by leaving temporary files in a directory if the host e.g. power failed during the write. It was decided that most globs ignore files which start . so there is no real risk.

**Comment by piojo** [comment]
[`File::AtomicWrite`](http://search.cpan.org/~jmates/File-AtomicWrite-1.16/lib/File/AtomicWrite.pm) looks quite solid.  We'd just need to make `CAF::FileWriter` use it instead of `LC::Check`, and enforce that its templates are always strong enough.

However, is it available on older RHELs?

**Comment by stdweird** [comment]
i did some further review:
* i can add support for mtime and backup
* supporting changes is very hard. now the changes are checked twice: once by diff (if in verbose mode), and by `LC::Check::file` code. i would like to use `Text::Diff` to compare and report any changes, and if a change exists, call `File::AtomicWrite` to write the changes

@ned21 can we use `Text::Diff`? it exists in EL6 and El7, not in 5. (but `File::AtomicWrite` does not exist anywhere)

**Comment by ned21** [comment]
Yes, that's fine. Both File::AtomicWrite and Text::Diff will need rpms created and shipped as part of the externals repo?

**Comment by stdweird** [comment]
ofcourse. only `Text::Diff` needs them for el5 though.

**Comment by stdweird** [comment]
@ned21 wrt `Text::Diff`, burrently jenkins has 1.41 installed (same version as el7 ships) and a unified diff looks
```
@@ -1 +1 @@
-garbage+test
```
(yes, on a single line).

with version 1.44 (current latest) the diff looks like
```
@@ -1 \+1 @@
-garbage
\ No newline at end of file
+test
```

requiring 1.44 implies that the perl-Text-Diff rpm should come from externals for el5-7

**Comment by stdweird** [comment]
apologies, moved to 17.2 due to lack of testing before 16.12

**Comment by jouvin** [comment]
March 17 workshop: [Fille::Atomic-based](https://github.com/quattor/CAF/pull/202) FileWriter should fix it. Must be tested.
