### ISSUE TITLE
CAF FileWriter set default file permissions

### ISSUE THREAD

**Issue by stdweird** [quattor/CAF#149]
`CAF::FileWriter` should set a default filemode, irrespective of the defined umask. proposal is to use `0644`

**Comment by stdweird** [comment]
@jrha @jouvin @ned21 please comment

**Comment by ned21** [comment]
This would only be a default? So any code where the author had specified a value would continue to work unchanged? I could potentially see this breaking a site where they were relying on a umask to ensure all files were 0600 or similar but in principle I think this is a good idea.

**Comment by stdweird** [comment]
@ned21 what we can do is add a `set_umask` method to CAF somewhere, and when this is used to set the umask, the FileWriter does not set this default.

and yes, this would be a default, if mode is specified, the specified mode is set, umask or no umask.

you should be aware that `LC::Check` sets default directory permissions if no mode is specified when creating e.g. the parent directory of a file; and that quite a few components have a default mode in the schema (e.g. metaconfig and filecopy), so also there umask is not relevant.

**Comment by ned21** [comment]
Sorry the problem I raised was hypothetical. I don't know of any site relying on umask and unless someone pops up in the comments then I think we should just make the defaults sensible and not complicate the code by providing an opt-out. If it does turn out to be a real issue then we could implement `set_umask`.

**Comment by stdweird** [comment]
Done in #243
