### ISSUE TITLE
test_caffileeditor.t unit test failing

### ISSUE THREAD

**Issue by jouvin** [quattor/CAF#150]
On my development machine (EL6), I cannot run successfully tests related to FileEditor. For example, any attempt to run `test-caffileeditor.t` results in:

```
Name "testapp::error" used only once: possible typo at src/test/perl/test-caffileeditor.t line 35.
Error unlinking file target/test/editor/27zwuNRksA using unlink0 at src/test/perl/test-caffileeditor.t line 15
src/test/perl/test-caffileeditor.t .. 
Dubious, test returned 25 (wstat 6400, 0x1900)
No subtests run 
```

I tried both with master and previous release... What trivial mistake did I do?

**Comment by stdweird** [comment]
given we run the tests on el5/6/7 before each release, i find this a bit strange. are you saying that the unittests from master fails on EL6 with this error?

**Comment by jouvin** [comment]
At least on my EL6 machine. There is may be something different in the test environment and what we run (which is pretty standard). At least the fix should not hurt!!

**Comment by stdweird** [comment]
@jouvin i'm just surprised that master unittests fail, i'll merge the fix
