### ISSUE TITLE
kerberos_process.t:lots of gssapi failure + uninitialized value

### ISSUE THREAD

**Issue by jouvin** [quattor/CAF#158]
`kerberos_process.t` produces several lines like below and they don't seem expected failures despite the test is considered to be passed successfully...

```
# VERBOSE FAIL: _gssapi_accept expected a GSSAPI::Context instance, got ref  instead.
Use of uninitialized value $class:: in concatenation (.) or string at src/test/perl/kerberos.t line 251.
```

**Comment by stdweird** [comment]
i'll check if https://github.com/quattor/CAF/pull/145 fixes this

**Comment by stdweird** [comment]
the uninitialised warnings are solved by the PR

**Comment by jouvin** [comment]
Confirmed, Closing the issue.
