### ISSUE TITLE
Test path.t failure

### ISSUE THREAD

**Issue by jouvin** [quattor/CAF#161]
On my SL6 development machine, `path.t` fails:

```
# VERBOSE FAIL: Unsupported LC::Check function no_lc_check_function
# DEBUG: 1 Ignoring/resetting previous existing fail: Unsupported LC::Check function no_lc_check_function
# DEBUG: 1 Ignoring/resetting previous existing error: *** : origexception LC_Check unknown dispatch
No root path(s) specified
 at src/test/perl/path.t line 269

#   Failed test 'directory_exists false on missing directory'
#   at src/test/perl/path.t line 270.

#   Failed test 'any_exists false on missing directory'
#   at src/test/perl/path.t line 272.
# DEBUG: 1 Ignoring/resetting previous existing fail: origfailure existence tests
# DEBUG: 1 Ignoring/resetting previous existing error: *** : origexception existence tests
```

Do I have something missing? Not sure why the test succeeded on GitHub...

**Comment by stdweird** [comment]
tests pass with blank EL6 VM and build_all_repos. can you mail me the whole output of 
```
QUATTOR_TEST_LOG_CMD_MISSING=1 QUATTOR_TEST_LOG_CMD=1 QUATTOR_TEST_LOG_DEBUGLEVEL=3 mvn clean test -Dunitttest=path.t
find target
```

**Comment by jrha** [comment]
Please don't assign milestones to issues unless they are release blocking issues (no evidence for this one yet) or they have an associated PR.

**Comment by jouvin** [comment]
@stdweird here is the log: [log.txt](https://github.com/quattor/CAF/files/259166/log.txt)

**Comment by jouvin** [comment]
@jrha I apologize it I did something wrong... Nevertheless, I always tend to assign a milestone to issue as I am afraid that an issue without a milestone will never be looked at. I could have put 16.6 but in this case decided 16.4 because I always find a problem in a test suspect and it may be the sign of something that will popup in the release process later... I may have been wrong....

**Comment by stdweird** [comment]
@jouvin the attached log has all tests passing. can you try to reproduce a failing one?

**Comment by jrha** [comment]
@jouvin no worries, we decided to keep a global backlog of unassigned issues and monitor it to prevent issues being lost rather than losing them while they are assigned to future releases. Neither system is perfect.

**Comment by jouvin** [comment]
@stdweird problem understood (sorry I awa in a meeting and didn't check that the log reproduced the error). It happens if you don't clean. Certainly nothing urgent then. But for me, it is a bad practice if we always need to run the clean phase... New log with the problem:
[log2.txt](https://github.com/quattor/CAF/files/259600/log2.txt)

**Comment by stdweird** [comment]
euhm, i never run without clean :smile:

**Comment by jrha** [comment]
I'm now seeing this on a clean SL6.7 VM while trying to `build_all_repos`

**Comment by stdweird** [comment]
@jrha can you pm me the gzipped output?

**Comment by jrha** [comment]
Sure, I'm just re-running to confirm.

**Comment by stdweird** [comment]
i ran build_all_repos on el65, el71 and el59 and all went ok

**Comment by jrha** [comment]
FWIW I also initially saw the failure to install `perl-enum` as well, so they may be something deeper wrong with the VM images.

**Comment by jrha** [comment]
@stdweird I've emailed the `build_all_repos` output to you.

**Comment by stdweird** [comment]
are you running the tests as root? if so, can you run the tests via https://github.com/quattor/release/blob/master/src/scripts/context_init_build_all_repos.sh

the tests fail on a premission restricted piece of code, but if root is allowed to ignore directory permissions, the tests can trigger the expected failure.

**Comment by jrha** [comment]
I am, always have. I'm lazy and it's highlighted some non-mocked code in the past.
I'll try running again as a non-root user.

**Comment by stdweird** [comment]
ok, i'll try to run th etests as root, and see if it is an root related issue or not.

**Comment by jrha** [comment]
Ok it passes fine as a unprivileged user, now dying on `rpmlint`, so new issue.

**Comment by jouvin** [comment]
Hit that problem again...  Log file [CAF_path_test.log.gz](https://github.com/quattor/CAF/files/799533/CAF_path_test.log.gz) attached.

**Comment by stdweird** [comment]
@jouvin thanks for the log. what filesystem is this? and you are running as non-root, right?
if you are runnign the tests to get rpms, you can get them from jenkins too https://jenkins1.ugent.be/view/Quattor/job/perl-CAF/lastBuild/org.quattor.client.libraries$perl-CAF/artifact/org.quattor.client.libraries/perl-CAF/16.12.1-SNAPSHOT/perl-CAF-16.12.1-SNAPSHOT.rpm

**Comment by jouvin** [comment]
Yes I am running non root... but I run tests to assess that I broke nothing, not to get RPMs! Thus my problem if I cannot run the tests reliably on my local SL6 machine...

**Comment by stdweird** [comment]
ok, and what filesystem are you using? and can you share a `env|sort` output? what OS is this? (i'm trying to gather some data, i have no obvious idea what the issue could be).
also, is it reproducable?

**Comment by jouvin** [comment]
@stdweird it seems to be my usual "mistake" of using `mvn` without `clean`. Obviously, as the tests create files, depending on the situation at the beginning of the test, the result may be different... To fix this, we should may be use a temporary directory created by `mktemp` instead of `target/test/check`.

**Comment by jouvin** [comment]
I personnally think that running clean should not be a requirement...

**Comment by jrha** [comment]
agreed
