### ISSUE TITLE
CAF::Process, $? and NoAction

### ISSUE THREAD

**Issue by ned21** [quattor/CAF#167]
I noticed a regression in some ncm- components when running in --noaction mode after upgrading to 16.2. The component would report an ERROR that a command had failed, even though it was never run (this is NoAction mode). The ERROR was being logged as a result of a check on $?, which CAF::Process documents as the correct way to check for errors from sub-processes. Downgrading perl-CAF and perl-LC did not resolve the problem, it was only when I reverted both ncm-ncd and ccm that the problem went away. Known working version is 14.10, I was unable to test anything between 14.10 and 16.2.

In NoAction mode, CAF::Process never sets $? so my hypothesis is that something in ncm-ncd and ccm are invoking subprocesses that causes $? to have a stale value when checked by the component. 

Is it possible to override or reset the value of $? or would we need to execute /bin/true instead?

**Comment by stdweird** [comment]
@ned21 it must be something like that. `$?` can be set by anything (it's also how `LC::Process` does it).
it's a pity the is not `local+1` scope or something like that :smile: 
i fixed it as part of cleanup/refactoring https://github.com/quattor/CAF/pull/168/files#diff-935c84ca8d8a9b56c500c070f0e885aaR152
