### ISSUE TITLE
FileWriter:: Log when a file has been updated

### ISSUE THREAD

**Issue by ned21** [quattor/CAF#185]
ncm-nss has this code to let the SA know when the file has been updated:

```
my $fh = CAF::FileWriter->open("/etc/nsswitch.conf",
                                   backup => ".OLD",
                                   owner => "root",
                                   group => "root",
                                   mode => 0444,
                                   log => $self,
                                );
print $fh join("", @new);
my $result = $fh->close();
if ($result) {
    $self->info("updated /etc/nsswitch.conf") unless $NoAction;
    ...
```

This logging/notification should be an intrinsic part of CAF::FileWriter.

**Comment by stdweird** [comment]
@ned21 There's now verbose logging on change https://github.com/quattor/CAF/blob/master/src/main/perl/FileWriter.pm#L348 and history is kept (and `ncm-ncd` spits it out (currenlty still only at the end, but i tought there was an issue somewhere to make this history reporting realtime)).

Is this sufficient?
