### ISSUE TITLE
Application.pm: no possibility to test if an option exists

### ISSUE THREAD

**Issue by jouvin** [quattor/CAF#210]
If I am right, there is currently no way to test if an option is defined in the context of an application. If using `option()` method with a non existing option, an error is printed saying that the option doesn't exist. It would be great to have either `option()` testing the exististence of the option and silently ignoring non existing option (this will result in an `undef` value returned).or to have a method to test the existence of the option. 

My preference would be to have `option()` ignore silently missing variables with a message logged if debug level >= 1. Testing a variable existence is as simple as:
```
$self->{CONFIG}->_exists($opt)
```

Having it done by `option()` would not require any change in existing code to get rid of the error message that happens if a variable is not defined. When a variable is required to exist, it will be enough to test if the value returned by `option()` is `undef`, as it is already the case.

**Comment by stdweird** [comment]
yes, it is a great pity that the `Appconfig` `->get()` method does not support defaults.
but you can already check if value is defined, using clunky code like https://github.com/quattor/CAF/blob/master/src/main/perl/Application.pm#L449
so you can support a default with `CAF::Application` `option` method as second argument, and handle the test with the `varlist` trickery.

**Comment by jouvin** [comment]
I know how to test a variable existence with AppConfig. This is in fact much simpler that the clunky code you mentioned. AppConfig has an "internal method" called `_exists()` that does exactly what is needed. And as said in AppConfig code, it is quite reasonable to use the internal API for simple things (I really don't expect this method to disappear or change! Less chance than a change in the internal structure...).

My issue is about changing the CAF::Application `option()` behaviour to avoid returning the AppConfig error message (using `_exists()`), just returning the `undef` value (which is IMO enough information for the caller). If in `option()` we have a logger we could log the error message a `verbose` and above.
