### ISSUE TITLE
CAF::Path: add a is_symlink() function

### ISSUE THREAD

**Issue by jouvin** [quattor/CAF#217]
If I understood properly the documentation, there is no trivial way of assessing that an existing file or directory is a symlink with `CAF::Path`, something that is sometimes desirable? What about adding  `is_symlink()` function that could be used in conjunction with other `xxx_exists()` function to check if an object is a symlink?

**Comment by stdweird** [comment]
adding sym/hardlink support is on the todo list. just testing is not enough, also creating a link is required and the maventools need support for the new caf methods.
