### ISSUE TITLE
CAF::Path xxx_exists() functions are not NoAction safe

### ISSUE THREAD

**Issue by jouvin** [quattor/CAF#218]
`xxx_exists()` functions test the file/directory/object existence even though NoAction is set, meaning they fail in the unit test context (where the file may not exist).

**Comment by stdweird** [comment]
`NoAction` is not a variable related to unittests, it means that no modifications to the state of a node are made. testing a file existence does not affect the state of system, so nothing is required.

for unittests, you need to fake the existence of the file, which is as simple as eg setting the contents of the file. it can be emtpy. (and a fake file also gets fake directories for free, so `directory_exists` on the parent will work).

**Comment by stdweird** [comment]
for an example see https://github.com/quattor/configuration-modules-core/pull/1045/files#diff-6e3fd2522886db53e341d16bd0bd7eddR43 which fakes the file test in https://github.com/quattor/configuration-modules-core/pull/1045/files#diff-9c90954db2b0a0810ad993d352b7d2e7R152

**Comment by jouvin** [comment]
No `set_file_contents()` doesn't work in this particular context because this is not creating a real file (if I am right) and thus `xxx_exists()` that expects a real file fails.

**Comment by stdweird** [comment]
what are you trying to test? the `CAF::Path` `_exists` methods are all mocked in `Test::Quattor` (unless there are some old build tools involved. 1.50 should have all required functionality)

**Comment by jouvin** [comment]
I'll try again but this morning I had a problem with `CAF::Path->file_exists()`...

**Comment by stdweird** [comment]
just to avoid a mistake @jrha made, `CAF::Path` has to be used as follows:
```perl

use parent qw(... CAF::Path);

...
   $self->file_exists();
...
```

**Comment by jouvin** [comment]
Would be good to have this documented in `CAF::Path` documentation (pod). I looked at this kind of info and didn't find it... This does not mean it is not there but probably in the middle of other things...

**Comment by jouvin** [comment]
Next question! How do you use it in a package like `pxelinux` where most functions are not methods (no `$self` defined)? I am not sure of the reason why this is like this, probably no good one...

**Comment by stdweird** [comment]
you can't use it (yet). the mocking uses `MockModule`, so requires instances of classes.

but i'm not sure it is something we should work on. cleaning up AII and making it a proper set of modules/classes (eg logging via `this_app` etc etc) is probably more worthwhile.

**Comment by jouvin** [comment]
After @stdweird explanation, everything works as expected!
