### ISSUE TITLE
CAF::Reporter struct logging fails on el5 due to missing strict TT mode

### ISSUE THREAD

**Issue by stdweird** [quattor/CAF#219]
Default TT on el5 (2.18) has no STRICT mode (STRICT mode makes TT render fails when trying to use undefined values in rendering).

I would really like to keep the strict mode for the struct logging, so my question is: can we have this different behaviour between el5 and el6/7.

on el5, you will have message with missing fields, on el6/7 you will have messages that complain that rendering failed (as part of the message).

this does not affect the structured logging itself, only the message that is generated and used by regular reporter (eg syslog).

this issue currently prevents CAF validation on el5 due to tests https://github.com/quattor/CAF/blob/master/src/test/perl/reporter.t#L236

**Comment by jrha** [comment]
I no longer care about EL5 compatibility... @ned21?

**Comment by ned21** [comment]
We very much care about EL5 support. :( Different (and less optimal) behaviour on older releases is fine.
