### ISSUE TITLE
CAF::FileEditor from source broken

### ISSUE THREAD

**Issue by stdweird** [quattor/CAF#237]
The diff from FileEditor with source is broken; regular close for FileEditor works by accident (it rereads the original contents). All thanks to typo.

**Comment by stdweird** [comment]
@jrha needless to say, blocking for 17.3

**Comment by stdweird** [comment]
the issue is much more severe than just a typo. it is a misinterpretation what `source` means. expect a PR soonish

**Comment by jrha** [comment]
:persevere:
