### ISSUE TITLE
CAF::FileWriter default permissions

### ISSUE THREAD

**Issue by stdweird** [quattor/CAF#241]
looks like with new FileWriter, the default permissions are changed from `644` to `600`. 

help is appreciated to point where exactly the old permissions were set.

**Comment by stdweird** [comment]
@jrha needless to say, this is blocking for a release. new nodes have `/etc/passwd` with `600` and this gives errors like https://access.redhat.com/solutions/2051343

**Comment by stdweird** [comment]
looks like (undocumented) defaults from LC and AtomicWrite
```
[stdweird@spikev ~]$ PERL5LIB=/usr/lib/perl perl -e 'use File::AtomicWrite;my $a = "a";File::AtomicWrite->write_file({file => "/tmp/fw/aw", input => \$a});'
[stdweird@spikev ~]$ PERL5LIB=/usr/lib/perl perl -e 'use LC::Check;LC::Check::file("/tmp/fw/lc", contents=>"a")'
updated /tmp/fw/lc
[stdweird@spikev ~]$ ls -l /tmp/fw/
total 8
-rw------- 1 stdweird stdweird 1 Apr 10 21:00 aw
-rw-rw-r-- 1 stdweird stdweird 1 Apr 10 21:01 lc
```

**Comment by stdweird** [comment]
the permissions are set by `File::Temp`, which is used by `File::AtomicWrite`. PR soonish...

**Comment by jrha** [comment]
:sob:

**Comment by stdweird** [comment]
more issues
LC: file: 0664 parentdir 0755
AtomicWrite: file 0600 parentdir 0775

the file perms are easy to fix, but the parentdir not that easy (the 0755 is a LC default builtin).
