### ISSUE TITLE
CAF::Process: Include sensitive option

### ISSUE THREAD

**Issue by alvarosimon** [quattor/CAF#254]
Sometimes you need to execute a command that includes a password for example. This is quite sensitive and we should avoid to show the command from the logs. 

We can avoid this if we include an `sensitive`   option within ` %opts`    in these cases. If the option is set then CAF::Process does not show the sensitive command from the log.

**Comment by ned21** [comment]
I think you can achieve this already by not setting the `log` option in `%otps` ? Or explicitly setting it to `undef`? (Obviously accompanied by a comment to say why logging has deliberately been disabled!)

**Comment by stdweird** [comment]
@ned21 i tought about it, but it's a bit drastic imho. 
if we would start supporting history in `CAF::process` (eg for auditing/tracing), that would make it impossible.
and i'd rather make `sensitive` an option that is support/known in all of CAF (like `keeps_state`).

**Comment by ned21** [comment]
OK, so this would allow everything else to be logged but except for the command line which makes sense. Going one step further, ideally we would only redact the argument that was sensitive.  How difficult would it be to able to nominate 1 or more elements of the command array to be replaced in the log output?

**Comment by stdweird** [comment]
currently sensitive is a boolean, but we could add a new option `redact` (a compiled regex pattern) that does search and replace with `***` in the logs (or all logs) or an index.

we could also wrap the sensitive bit in an arrayref, eg `$cmd = [qw(set passwd user), [$password]]`
to detect the not to be reported portions?

**Comment by ned21** [comment]
Sounds good. So let's go with the boolean for now and we can always add the redact later.
