### ISSUE TITLE
Filewriter: modify permissions when content is unmodified

### ISSUE THREAD

**Issue by stdweird** [quattor/CAF#259]
Currently when the content is unmodified, other changes like owner/mode are not forced to the file.
I propose to fix this and report any changes to owner and/or mode also as a changed file on close.

**Comment by stdweird** [comment]
@jrha @ned21 feedback pls...

**Comment by jrha** [comment]
Well it sounds like the write thing to do.

**Comment by ned21** [comment]
+1 from me
