### ISSUE TITLE
CAF::FileStatus

### ISSUE THREAD

**Issue by jouvin** [quattor/CAF#69]
Several components (see https://github.com/quattor/configuration-modules-grid/issues/58 for an example) rely on `LC::Check` features that are not implemented in `CAF::FileXxx`. This is mainly:
- `LC::Check::directory`: creation of a directory if it doesn't exist
- `LC::Check::status` for directories: allow to define owner/group/perm... for directories
- `LC::Check::absence`: remove a file/directory if it exists
- `LC::Check::symlink`: symlink management

Also `LC::Check::status` for file can be executed through `CAF::FileEditor` but this is a bit of an overkill to use this interface if you just want to check/update file metadata.

It may be useful to have a `CAF::FileStatus` module that will act as a wrapper over `LC::Check` or other standard Perl module/functions (e.g. `File::Path`) to implement high-level features that can be tested (mocked) as other `CAF` modules.

Also for directory, it may be interesting to offer a `directory` function that combines `LC::Check::directory` and `LC::Check::status` as this is not very efficient to have to call 2 functions... This would be more consistent with `CAF::FileXxx` modules.

**Comment by jrha** [comment]
Or the 15.4 cycle...

**Comment by jrha** [comment]
Or the 15.6 cycle...

**Comment by stdweird** [comment]
@ned21 you can't mock the perl builtins `-f` etc. Other nice thing would be integration with `Test::Quattor`, so when you fake the contents of a file with `set_file_contents`, a file existence test should report this fake file as being present (and the whole subtree should be testable as exsting directories).

i'm willing to do some effort here, but i need something more than just filestatus, i need some basics like
* `LC::Check::_unlink` with directory support
* existence checks for directory (-d), file (-f || -l) or anything (-e || -l)
* mkdir (also for mocking)

this can all go in one module imho, but it will need a better name. or more than one module.
i would also need some advise how reporting would be handled (do we throw errors? log errors? store error message in some magic exported variable?)

**Comment by stdweird** [comment]
see also
* https://github.com/quattor/configuration-modules-core/issues/648
* work done in https://github.com/quattor/configuration-modules-core/pull/615/files#diff-03b83223101921d4405f8416363c3a20R359

**Comment by jouvin** [comment]
Closing this issue after https://github.com/quattor/CAF/issues/142 and https://github.com/quattor/CAF/issues/255.
