### ISSUE TITLE
FileEditor add after newline

### ISSUE THREAD

**Issue by stdweird** [quattor/CAF#79]
we ran into a bug in the `ncm-named` component where `CAF::FileEditor` does a `add_or_replace` to the end of the file, but the file itself didn't end in a newline. (it broke resolv.conf, making the machine useless).

i plan to add support to check that add happens after a newline (if no newline is found, add/insert one), but i would like to make it default (but if you really know what you are doing, youn can disable this).

is there any objection against this? (besides being backward in-compatible)?

**Comment by jrha** [comment]
No objection from me.
